.TH haskalc 1 "2021-09-27" "Benjamin Stürz"

.SH NAME
haskalc - a calculator written in the Haskell programming language

.SH SYNOPSIS
.SY haskalc
.YS

.SH DESCRIPTION
.I haskalc
is a simple calculator written in the Haskell programming language.

.SH USAGE
The calculator currently supports
.I integers
and
.I floating-point numbers
and these basic \fIoperators\fR:
.PP
.RS 5
+ (addition)
.RE
.RS 5
- (subtraction)
.RE
.RS 5
* (multiplication)
.RE
.RS 5
/ (division)
.RE
.RS 5
% (modulo)
.RE
.RS 5
^ (exponentiation)
.RE
.RS 5
= (assignment)
.RE
.PP
It also supports variables (like pi) and functions (eg. sin(10)).
.RE
To exit the calculator write
.I exit
or send an EOF-character with
.I Ctrl+D\fR.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
